name: Deploy to Laravel Forge
description: Deploy to Laravel Forge with GitHub Actions
branding:
  icon: zap
  color: green
inputs:
  forge-api-token:
    description: Your Forge API Token
    required: true
  forge-server-id:
    description: Your Forge Server ID
    required: true
  forge-site-id:
    description: Your Forge Site ID
    required: true
  env-file-path:
    description: Path to the .env file
    required: false
  deploy-script-path:
    description: Path to the deploy script
    required: false
runs:
  using: composite
  steps:
    - name: Run the deploy script
      run: |
        ${{ github.action_path }}/script.sh \
          "${{ inputs.forge-api-token }}" \
          "${{ inputs.forge-server-id }}" \
          "${{ inputs.forge-site-id }}" \
          "${{ inputs.env-file-path }}" \
          "${{ inputs.deploy-script-path }}"
      shell: bash
